Repository HaronCode/Gemini, pull requests merged in 2020-03, with the labels that each got.

#6 feature/extended lifecycle
  build.gradle
  dependencies.gradle
  gemini-android/build.gradle
  gemini-android/src/main/java/com/haroncode/gemini/android/ExtendedLifecycle.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/ExtendedLifecycleFragment.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/ExtendedLifecycleObserver.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#7 tech/update connection arch
  build.gradle
  gemini-android/build.gradle
  gemini-android/src/main/java/com/haroncode/gemini/android/AndroidBinder.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/BindingStrategy.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/LifecycleStrategy.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/StoreViewConnector.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/ViewBinding.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/binder/MainThreadConnectionBinder.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/extended/AndroidLifecycleEvent.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/extended/EventExtendedLifecycleObserver.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/extended/ExtendedLifecycle.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/extended/ExtendedLifecycleFragment.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/extended/ExtendedLifecycleObserver.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/lifecycle/AndroidStoreLifecycle.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/lifecycle/RxLifecycleEventObserver.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/lifecycle/StoreLifecycleEventObserver.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/strategies/ResumePauseStrategy.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/strategies/StartStopStrategy.kt
  gemini-common/build.gradle
  gemini-common/src/main/java/com/haroncode/gemini/common/Common+Extension.kt
  gemini-core/build.gradle
  gemini-core/src/main/java/com/haroncode/gemini/binder/BaseConnectionBinder.kt
  gemini-core/src/main/java/com/haroncode/gemini/connection/BaseConnectionRule.kt
  gemini-core/src/main/java/com/haroncode/gemini/connection/ConnectionRule.kt
  gemini-core/src/main/java/com/haroncode/gemini/connection/EventListenerConnection.kt
  gemini-core/src/main/java/com/haroncode/gemini/connection/NavigationConnection.kt
  gemini-core/src/main/java/com/haroncode/gemini/connection/StoreAutoDisposeConnectionRule.kt
  gemini-core/src/main/java/com/haroncode/gemini/connector/BaseStoreConnector.kt
  gemini-core/src/main/java/com/haroncode/gemini/connector/StoreConnector.kt
  gemini-core/src/main/java/com/haroncode/gemini/connector/StoreLifecycle.kt
  gemini-core/src/main/java/com/haroncode/gemini/coordinator/Coordinator.kt
  gemini-core/src/main/java/com/haroncode/gemini/core/ConnectionBinder.kt
  gemini-core/src/main/java/com/haroncode/gemini/core/EventListener.kt
  gemini-core/src/main/java/com/haroncode/gemini/core/StoreLifecycle.kt
  gemini-core/src/main/java/com/haroncode/gemini/store/AbstractStore.kt
  gemini-core/src/main/java/com/haroncode/gemini/store/BaseStore.kt
  gemini-core/src/main/java/com/haroncode/gemini/store/JustReducerStore.kt
  gemini-core/src/main/java/com/haroncode/gemini/store/OnlyActionStore.kt
  gemini-core/src/test/kotlin/com/haroncode/gemini/binder/BaseConnectionBinderTest.kt
  gemini-core/src/test/kotlin/com/haroncode/gemini/common/TestConnectionBinder.kt
  gemini-core/src/test/kotlin/com/haroncode/gemini/connector/BaseStoreConnectorTest.kt
  gemini-core/src/test/kotlin/com/haroncode/gemini/core/BaseStoreTest.kt
  gradle.properties
  settings.gradle
Labels: tech

#9 feature/add kotlin dsl module
  gemini-android/src/main/java/com/haroncode/gemini/android/connection/DelegateConnectionRuleFactory.kt
  gemini-core/src/main/java/com/haroncode/gemini/connection/AutoStoreDisposeConnectionRule.kt
  gemini-core/src/main/java/com/haroncode/gemini/connection/EventListenerConnection.kt
  gemini-core/src/main/java/com/haroncode/gemini/connection/dsl/BaseConnectionRuleDsl.kt
  gemini-core/src/main/java/com/haroncode/gemini/connection/util/FlowableTransformer+Extension.kt
  gemini-core/src/test/kotlin/com/haroncode/gemini/core/BaseStoreTest.kt
  gemini-dsl/build.gradle
  gemini-dsl/src/main/java/com/haroncode/gemini/dsl/BaseConnectionRuleDsl.kt
  gemini-dsl/src/main/java/com/haroncode/gemini/dsl/ConnectionFactoryDsl.kt
  gemini-dsl/src/main/java/com/haroncode/gemini/dsl/Mapper.kt
  gemini-dsl/src/main/java/com/haroncode/gemini/dsl/Transformer.kt
  settings.gradle
Labels: enhancement

#10 ExtendedLifecycleObserver refactoring with savedstate
  build.gradle
  dependencies.gradle
  gemini-android/build.gradle
  gemini-android/src/main/java/com/haroncode/gemini/android/StoreViewConnector.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/extended/EventExtendedLifecycleObserver.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/extended/ExtendedLifecycle.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/extended/ExtendedLifecycleFragment.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/extended/ExtendedLifecycleObserver.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/lifecycle/StoreLifecycleEventObserver.kt
Labels: enhancement

#11 DefaultLifecycleObserver replaced with LifecycleObserver
  dependencies.gradle
  gemini-android/build.gradle
  gemini-android/src/main/java/com/haroncode/gemini/android/StoreViewConnector.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/extended/EventExtendedLifecycleObserver.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/extended/ExtendedLifecycleObserver.kt
  gemini-android/src/main/java/com/haroncode/gemini/android/lifecycle/StoreLifecycleEventObserver.kt
Labels: enhancement

#12 bug/fix bug with restore state
  gemini-android/src/main/java/com/haroncode/gemini/android/lifecycle/StoreLifecycleEventObserver.kt
Labels: bug

#13 tech/publishing plugin
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/GeminiPublishingPlugin.groovy
  buildSrc/src/main/groovy/GeminiPublishingPluginExtension.groovy
  buildSrc/src/main/groovy/data/AuthData.groovy
  buildSrc/src/main/groovy/data/PublishData.groovy
  buildSrc/src/main/groovy/task/AndroidJavadocsJarTask.groovy
  buildSrc/src/main/groovy/task/AndroidJavadocsTask.groovy
  buildSrc/src/main/groovy/task/AndroidSourcesJarTack.groovy
  buildSrc/src/main/groovy/task/JavadocsJarTask.groovy
  buildSrc/src/main/groovy/task/SourceJarTask.groovy
  gemini-android/build.gradle
  gemini-common/build.gradle
  gemini-core/build.gradle
  gemini-dsl/build.gradle
  gradle.properties
Labels: tech
